name: make-linter
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: pip install --user poetry
      - name: my check
        run: make lint